timing: True
debug: False
stop_at_error: False

likelihood:
  des_y3.DES_cosmic_shear:
    path: ./external_modules/data/des_y3
    data_file: DES_Y3_no_scale_cut.dataset
    print_datavector: False
    non_linear_emul: 1
    kmax_boltzmann: 5.0

params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.65
    proposal: 0.4
    latex: 10^9 A_\mathrm{s})
    drop: true
    renames: A
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 5
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.004
    proposal: 0.004
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}
    drop: true
  mnu:
    value: 0.06
  tau:
    value: 0.05
    latex: \tau_\mathrm{reio}
  omegal:
    latex: \Omega_\Lambda
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  sigma8:
    latex: \sigma_8
  DES_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{DES}^1
  DES_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{DES}^2
  w:
    value: -1
    latex: w0
  w_growth:
    value: -1
    latex: w_\mathrm{growth}
  omegam_growth:
    # -100 is a flag that implies omegam_growth = omegam_m
    value: -100
    latex: \Omega_\mathrm{m}^\mathrm{growth}
  #Galaxy bias, shear calibration, baryons do not enter emulation
  # WL photo-z errors
  DES_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^1
  DES_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^2
  DES_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^3
  DES_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{s,DES}^4
  DES_A1_1:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.5
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,DES}^1
  DES_A1_2:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,DES}^2
  DES_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,DES}^3
  DES_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,DES}^4
  DES_A1_5:
    value: 0
    latex: A_\mathrm{1-IA,DES}^5
  DES_A2_1:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: -1.36
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{2-IA,DES}^1
  DES_A2_2:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: -2.5
      scale: 0.5
    proposal: 0.5
    latex: A_\mathrm{2-IA,DES}^2
  DES_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,DES}^3
  DES_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,DES}^4
  DES_A2_5:
    value: 0
    latex: A_\mathrm{2-IA,DES}^5
  DES_BTA_1:
    prior:
      min: 0
      max: 2
    ref:
      dist: norm
      loc: 1
      scale: 0.15
    proposal: 0.1
    latex: A_\mathrm{BTA-IA,DES}^1
  DES_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^2
  DES_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^3
  DES_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^4
  DES_BTA_5:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^5
  #shear calibration need to be set to 0 for training emulators
  DES_M1:
    value: 0.0
    latex: m_\mathrm{DES}^1
  DES_M2:
    value: 0.0
    latex: m_\mathrm{DES}^2
  DES_M3:
    value: 0.0
    latex: m_\mathrm{DES}^3
  DES_M4:
    value: 0.0
    latex: m_\mathrm{DES}^4
  DES_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{DES}^1
  DES_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{DES}^2
  DES_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{DES}^3
  DES_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{DES}^4


theory:
  camb:
    path: ./external_modules/code/CAMB
    stop_at_error: False
    use_renames: True
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.15
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20

emulator:
  io:
      savedir: ./projects/des_y3/emulator_output/emu_validation/lhs/dvs_for_training_50k    
      save_train_data: true             
      save_intermediate_model: true
  training:
      dv_fid: ./projects/des_y3/data/Y3_unblinded_final.txt
      chi_sq_cut: 8e+4
      n_train_iter: 1
      n_lhs: 50000 
      n_resample: 9600
      #n_resample: 96 #KZ debug
      emu_type: nn
      batch_size: 32
      n_epochs: 100
  shear_calib:
      mask: ./projects/des_y3/data/emu_files/shear_calib_mask.npy  ##!! this is wrong, fixed later when sampling
      prior_std: 0.005, 0.005, 0.005, 0.005, 0.005
  baryons:
      n_pcas_baryon: 0
      prior_Q1: -3., 12.
  sampling:
      scalecut_mask: ./projects/des_y3/data/3x2pt_baseline.mask    ##!! this is wrong, fixed later when sampling
      #sampling here doesn't matter if n_train_iter=1, but still save here for comparison
      n_mcmc: 10000
      #n_mcmc: 10 #KZ debug
      n_emcee_walkers: 120
      n_burn_in: 5000
      #n_burn_in: 0 #KZ debug
      n_thin: 5
      #n_thin: 1 #KZ debug
      temper0: 0.05 #THIS has full control now, no increment, no minimum
      temper_increment: 0.1
  probe: 'cosmic_shear'


output: ./projects/des_y3/chains/generate_dv_emu_1